name: "Multi Event pipeLine " # Name of pipeline
on:
      push:  # Event: whenever a push is made to the repository on the main/test branch
        branches:
            - main
            - test
      pull_request:
        branches:
            - main



jobs:
    on-push:
        if: github.event == 'push'
        runs-on: ubuntu-latest
        steps:
           - name: "Running on main branch"
             run: echo "Running on main push"
    on-pull-request:
        if: github.event == 'pull_request'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on pull request"
              run: echo "Running On pull Request"


